application:
  name: gestionEcoleWeb
  project: gestionecoleweb
  cloud_region: aws/af-south-1
databases:
- type: postgresql
  version: "11"
  name: my-postgresql-database
- type: mysql
  version: "5.7"
  name: my-mysql-8628210
routers:
- name: main
  routes:
  - application_name: gestionEcoleWeb
    paths:
    - /*
