application:
  name: gestionEcoleWebBD
  project: gestionEcoleWebBD
  cloud_region: aws/us-west-2
  publicly_accessible: true
databases:
- type: mysql
  version: "8.0"
  name: my-db
routers:
- name: main
  routes:
  - application_name: gestionEcoleWebBD
    paths:
    - /
